### ISSUE TITLE
Tauola++

### ISSUE THREAD

**Issue by swayand** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#10]
Hi All,

why we don't use the central installed tauola version. e.g /cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/tauolapp/1.1.5-cms2 (which works with CMSSW_7_1_5). Therefore one only need to update tauspinner.xml, which can be done by me. If you have any doubts about it, pleas raise your voice. 

Cheers
Stefan

**Comment by rfriese** [comment]
If it works, go for it. I implemented the tauspinner stuff two years ago. Back then, this option was either not available or at least not known to me.

**Comment by swayand** [comment]
It worked for me. It was also already in the repository, but when it was removed due to the to large merge commit from Artur, and afterwards it wasn't followed up anymore. 
So i made the change online, but i didn't modify the checkout script. If it works for everyone than we can also remove the local installation of tauspinner in the checkout script.

**Comment by rfriese** [comment]
Hi Stefan,
I'm working on a transition to CMSSW8 with our analysis, which is becoming necessary at some point.

Can you please push the changes to avoid this extra checkout? I tried it, but got compiler warnings. I don't want to spend time on already solved problems.

**Comment by swayand** [comment]
Hi Raphael,

the changes are already inside ;) 
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/Kappa_2_1/scripts/checkout_packages.sh#L63-L64
So i will close this topic.

FYI
If you make the transition, you must check if the tauola version we use:
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/Kappa_2_1/data/tauspinner.xml#L6
Is also compiled with the same SCRAM_ARCH, if not you can just take an other tauola version.
