### ISSUE TITLE
Difference between similar Filters?

### ISSUE THREAD

**Issue by ArturAkh** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#11]
Hi all,

As a newcomer, I haven't full overview over Artus code yet. But my impression is, that there are a lot of similar Filters in Artus code:

(1) https://github.com/artus-analysis/Artus/blob/master/KappaAnalysis/interface/Filters/MaxObjectsCountFilters.h

(2) https://github.com/artus-analysis/Artus/blob/master/KappaAnalysis/interface/Filters/MinObjectsCountFilters.h

(3) https://github.com/artus-analysis/Artus/blob/master/KappaAnalysis/interface/Filters/ObjectsCountFilters.h

(4) https://github.com/artus-analysis/Artus/blob/master/KappaAnalysis/interface/Filters/ValidObjectsFilters.h

As I looked into their code, I concluded the following:

- (4) is a special case of (2): (4) is (2) with MinNMuons = 1
- (3) could be achieved through a combination of (1) and (2): e.g. MinNMuons = 2 and MaxNMuons = 2
- All these Filters have ValidObjects as input
---> (3) and (4) are not needed.

Am I right with my conclusion, or do I miss something?

Furthermore, there are additional Filters in HiggsToTauTau repository, which do the same thing for LooseObjects:

(5) https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/interface/Filters/MaxLooseObjectsCountFilters.h
(6) https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/interface/Filters/LooseObjectsCountFilters.h

So my impression: There are 4 Filters for Artus-people and even more (=6) Filters for KITHiggsToTauTau-people, that are applied on one object.

Wouldn't it be better to have one Filter per object, that can do all operations (1) - (6)?

Cheers,

Artur

**Comment by rfriese** [comment]
Is this still open?

**Comment by ArturAkh** [comment]
Nope, is closed. I guess I forgot to close it in this repository

**Comment by ArturAkh** [comment]
I'll close it
