### ISSUE TITLE
HiggsAnalysis-HiggsToTauTau-auxiliaries repository

### ISSUE THREAD

**Issue by rcaspart** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#14]
Dear all,

as we are in the process of deprecating the HiggsAnalysis-HiggsToTauTau-auxiliaries repository I would vote for removing it from our setup script (especially as it adds quite some unnecessary(?) size to the CMSSW area).
Are there any objections to this? If not I will do so by the end of today.

Cheers,
Rene

**Comment by fcolombo** [comment]
I would go for removing this from the scripts in all the branches used at the moment. If you check out now, this "auxiliaries" folder has a size of ~3 Gb (!!) and it does not seem to contain anything useful for the current 13 TeV analyses.
