### ISSUE TITLE
Yields used for Background estimations

### ISSUE THREAD

**Issue by rcaspart** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#17]
Currently when estimating the yields for backgrounds from control regions we use the function PoissonYield. This function currently determines the yield based on bins in the selected plotting range without taking into account the over- and underflow bins. For our "normal" use cases the difference between both should be negligibly small (given that there are few over- and underflow entries), however when looking at plotting ranges where the over- and underflow are non-negligibly this will lead to differences in the result.
I personally think the right way to proceed would be to include the over- and underflow bins for these calculations. The function mentioned before is so far only used in the background estimation-modules and hence seems to be the ideal place for this change. Does anyone of you have any objections to or strong opinion on introduce this change there?

[*] https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/Kappa_2_1/python/tools.py#L14

**Comment by fcolombo** [comment]
I think that looking at the yield on the complete phase space and not only in the range of the particular plot that one is producing, is the approach which is physically more correct, right?
If so, I would go for the change.

**Comment by roger-wolf** [comment]
Hi Fabio, agreed!
