### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by swayand** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#21]
Hi

in the file
data/Samples/DCAP_collection_MSSM_Run2Analysis.txt 
there are some Higgs signals mass points which are not included in our actual skimming procedure (https://github.com/KappaAnalysis/Kappa/blob/CMSSW_7_6_X/Skimming/higgsTauTau/samples/13TeV/Fall15_SM_Analysis.conf). Therefore some Higgs*_most_recent.txt files are pointing to some old files. It would be very nice if some expert could cross check this an update the skimming config.

**Comment by rcaspart** [comment]
The Samples are added now
