### ISSUE TITLE
Writing out of four-momenta

### ISSUE THREAD

**Issue by thomas-mueller** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#24]
Dear all,

You might have noted, that I added the functionality to write out RMFLV objects with the LambdaNtupleConsumer (https://github.com/artus-analysis/Artus/commit/cff1e8bbf67af384fb1cb15879e979c1b39ee980). I would like to ask for your opinion about this: Do you think it could be a good idea to reduce the number of branches in the Run2Analysis outputs (not in the sync ntuples of course) by writing out the RMFLV objects directly? I think, there will be no limitations for the postprocessing and we would ideally only store four floats per Lorentz vector in our ntuples.

Regards,
Thomas

**Comment by rfriese** [comment]
Isn't this implemented already?

**Comment by thomas-mueller** [comment]
No, they are just added in some cases and therefore it leads to unmeaningful increase of storage consumtion. But I am hesitating to change it completely. The first reason is my time, but then there are also issues like that we use now also the Run2 configs for the sync ntuples, that are required to be flat ntuples.

**Comment by rfriese** [comment]
After one year of no progress: Can we close this issue?

**Comment by thomas-mueller** [comment]
My opinion is, that this is still something that we should follow up once the SM/MSSM analyses are published. We should clean up the list of quantities to be written out in order to save storage space.
