### ISSUE TITLE
Artus has become slow - very slow

### ISSUE THREAD

**Issue by rfriese** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#33]
Dear all,

I already had a quick survey on the Artus runtime. The feeling is consistent that it has somehow become slow. I checked that on an input 2015 DYJetsMToLLM50 sample with today's configuration and the ones from a Run that finished on Mai, 31st. I disabled SVFit to make sure this isn't the problem. The result is clear: Today it took nearly 8 instead of 3.5 minutes with the status from two months ago. Since startup time hasn't changed so much (not measured, just my gut feeling) the throughput in events/s has really drastically changed by around a factor of 2.

Does anyone have any idea what might be the reason?

Cheers,
Raphael

**Comment by rfriese** [comment]
Update:
I still didn't finish my 2015 run. with report.py -R TimeReport you can see how much time a run is consuming. 

Consumed wall time: 5466h 10min 09sec (ongoing)
Consumed wall time: 644h 23min 54sec 

That's already a factor of 10 and increasing. I'm going to test if it's related to the DESY dCache.

If you get any news & insights, please post them here.
Cheers

**Comment by rfriese** [comment]
Rene just had the proposal to read the SVFit caches from /pnfs instead of dcap directly. It might be that the NFS caching eliminates our problem. Nevertheless, this only works on the NAF and we keep on searching for a generic solution. Just to let you know that this workaround helps.

In Numbers:
GluGluHToTauTauM125 in 38 jobs,
- reading caches from /pnfs: total Runtime 2:40h
- reading caches from dcap: total Runtime 12:00h
- not reading caches: total Runtime 2:30h

**Comment by thomas-mueller** [comment]
Hi Raphael,

I just want to comment that Root has some options to improve/accelerate reading from remote trees (e.g. the decision when the number of entries is read for the first time). I have done some work on this in the Artus core in the early days of Artus, but I have no time and good internet connection now to look into the details. You know where to find the Artus core...

For the Aachen group reading from NFS@NAF is no option at all. Please keep this in mind while searching for improvements.

Regards, Thomas

**Comment by rfriese** [comment]
Marcus gave me the game-changing hint. The problem is the total number of connections that in have to be held to the dcache while reading the files. Transferring them is not a problem. He suggested to copy them to worker node so that the connection can be closed.

ROOT offers a cool feature: it allows to open a ROOT file from remote and putting it into a temporary folder first (option "CACHEREAD" from TFile::Open). I put this to the SVFitTools (*) and got also the good runtime of around 2:30h for the whole GluGluH2Taus M125 GeV MC. If worker nodes share /tmp/ directories it might even happen that two jobs can access the same caches.

Cheers

(*) https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/commit/15697edb181e16bd91789cf63b3f8e3686fec0a9

**Comment by rfriese** [comment]
a lot has happened an the original issue seems to be solved
