### ISSUE TITLE
fully hadronic background estimation broken

### ISSUE THREAD

**Issue by rfriese** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#41]
Dear all,

after fixing the obvious things there's still something broken in the tt background estimation when comparing the status of 19th october:
http://www-ekp.physik.uni-karlsruhe.de/~friese/plots_archive/2016_11_04/old/
with today:
http://www-ekp.physik.uni-karlsruhe.de/~friese/plots_archive/2016_11_04/new/
while the plots above are done with an Artus run on the old skims, the problem does not disappear with the new one (MVA MET based):
http://www-ekp.physik.uni-karlsruhe.de/~friese/plots_archive/2016_11_04/newinputs/

Does anyone know where the problem might be? As I already wrote in my mail, it's not possible to tackle it easily with the usual approach. Artus is for all plots on the master.

Cheers,
Raphael

**Comment by anehrkor** [comment]
I think this has been solved, hasn't it?

**Comment by rfriese** [comment]
yes, thanks for the reminder.
