### ISSUE TITLE
Share svfit caches among all pipelines

### ISSUE THREAD

**Issue by thomas-mueller** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#5]
One could think about making the tree (https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/interface/Utility/SvfitTools.h#L177) and look-up table (https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/interface/Utility/SvfitTools.h#L178) for the svfit caches static in order to be able to share them among multiple pipelines. If the cache was shared among multiple pipelines, it would not be necessary to calculate svfit multiple times for the same inputs (as it happens now for example for the different JEC pipelines, that have no influence on svfit inputs).

**Comment by rfriese** [comment]
stale topic, anyone still interested?
