### ISSUE TITLE
Dataset query problem

### ISSUE THREAD

**Issue by thomas-mueller** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#55]
Dear experts,

I have problems running this Artus command:
```bash
HiggsToTauTauAnalysis.py @HiggsAnalysis/KITHiggsToTauTau/data/ArtusWrapperConfigs/Run2CPStudies_Nominal.cfg -f 1 -i HiggsAnalysis/KITHiggsToTauTau/data/Samples/XROOTD_sample_GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg_recent.txt
```
which produces
```
The following query expected 1 samples, but found 2:
{'campaign': 'RunIISummer16MiniAODv2',
 'energy': '13',
 'extension': '',
 'format': 'MINIAOD',
 'generator': 'powheg',
 'process': 'GluGluHToTauTauM125',
 'scenario': 'PUMoriond17'}
found the following matching samples: 
[u'GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-pythia8',
 u'GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg']
```
as output. This might be related to non-optimal nicknames, but my understanding is, that manually changing nicknames is no option in our current setup (correct me if I am wrong). The problem is the generator `powheg`, which also matches with `powheg-pythia8`. I tried the following changes:
```
diff --git a/python/higgstotautauanalysiswrapper.py b/python/higgstotautauanalysiswrapper.py
index 62e4655..f070064 100644
--- a/python/higgstotautauanalysiswrapper.py
+++ b/python/higgstotautauanalysiswrapper.py
@@ -5,12 +5,13 @@ import Artus.Utility.logger as logger
 log = logging.getLogger(__name__)
 
 import os
+import re
+import sys
 
 import Artus.KappaAnalysis.kappaanalysiswrapper as kappaanalysiswrapper
 import Artus.Utility.jsonTools as jsonTools
 import Artus.Utility.tools as tools
 
-import sys
 
 class HiggsToTauTauAnalysisWrapper(kappaanalysiswrapper.KappaAnalysisWrapper):
 
@@ -63,27 +64,27 @@ class HiggsToTauTauAnalysisWrapper(kappaanalysiswrapper.KappaAnalysisWrapper):
                if not "NumberGeneratedEvents" in self._config or (int(self._config["NumberGeneratedEvents"]) < 0):
                        from Kappa.Skimming.registerDatasetHelper import get_n_generated_events_from_nick
                        from Kappa.Skimming.datasetsHelper2015 import isData
-                       n_events_from_db = get_n_generated_events_from_nick(self._config["Nickname"])
+                       n_events_from_db = get_n_generated_events_from_nick(re.sub("^", "^", re.sub("$", "$", re.sub("_", "$_^", self._config["Nickname"]))))
                        if(n_events_from_db > 0):
                                self._config["NumberGeneratedEvents"] = n_events_from_db
-                       elif not isData(self._config["Nickname"]):
+                       elif not isData(re.sub("^", "^", re.sub("$", "$", re.sub("_", "$_^", self._config["Nickname"])))):
                                log.fatal("Number of Generated Events not set! Check your datasets.json for nick " + self._config["Nickname"])
                                sys.exit(1)
 
                if not ("CrossSection" in self._config) or (self._config["CrossSection"] < 0):
                        from Kappa.Skimming.registerDatasetHelper import get_xsec
                        from Kappa.Skimming.datasetsHelper2015 import isData
-                       xsec = get_xsec(self._config["Nickname"])
+                       xsec = get_xsec(re.sub("^", "^", re.sub("$", "$", re.sub("_", "$_^", self._config["Nickname"]))))
                        if(xsec > 0):
                                self._config["CrossSection"] = xsec
-                       elif not isData(self._config["Nickname"]):
+                       elif not isData(re.sub("^", "^", re.sub("$", "$", re.sub("_", "$_^", self._config["Nickname"])))):
                                log.fatal("Cross section for " + self._config["Nickname"] + " not set! Check your datasets.json")
                                sys.exit(1)
 
                if not ("GeneratorWeight" in self._config):
                        from Kappa.Skimming.registerDatasetHelper import get_generator_weight
                        from Kappa.Skimming.datasetsHelper2015 import isData
-                       generator_weight = get_generator_weight(self._config["Nickname"])
+                       generator_weight = get_generator_weight(re.sub("^", "^", re.sub("$", "$", re.sub("_", "$_^", self._config["Nickname"]))))
                        if(generator_weight > 0 and generator_weight <= 1.0):
                                self._config["GeneratorWeight"] = generator_weight
```
and
```
diff --git a/Skimming/python/registerDatasetHelper.py b/Skimming/python/registerDatasetHelper.py
index 6bedb24..6d5342d 100755
--- a/Skimming/python/registerDatasetHelper.py
+++ b/Skimming/python/registerDatasetHelper.py
@@ -263,7 +263,7 @@ def query_result(query, expect_n_results = 1):
                                matches = False
                                continue
                        if query[name] == None: continue
-                       if not (re.match('\\b'+str(query[name]).replace("_", "")+'\\b', str(attribute).replace("_", "")) != None):
+                       if not (re.search(str(attribute).replace("_", ""), str(query[name]).replace("_", "")) != None):
                                matches = False
                                continue
                if matches:
```
These solve the issue but cause problems at other places where the queries are used (e.g. for plotting). It is not clear to my, how to solve this problem properly and it would be nice if somebody who is more familiar with it / who wrote this could give me some hints/instructions what to look at. As this problem makes it impossible to process the mentioned sample, this is a rather urgent issue. Thanks for your help.

Regards,
Thomas

**Comment by ArturAkh** [comment]
Hi Thomas,

After multiple GluGluHToTauTau datasets have been added:

https://github.com/KappaAnalysis/Kappa/commit/c6b2dfb00655811488abbdd20b94e5d721fe6ffc#diff-ff1341b01af4f8f1a595138589aa105eR5283

You have now also to specify the "generator" in the query of samples_run2_2016.py for the dataset, e.g.:

https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/commit/c2a4e33cb8a9742837911a7119afa1bda20ede05

Cheers,

Artur

**Comment by thomas-mueller** [comment]
Thanks for your quick reply, Artur.

My problem are these lines:
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/python/higgstotautauanalysiswrapper.py#L66
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/python/higgstotautauanalysiswrapper.py#L76
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/python/higgstotautauanalysiswrapper.py#L86
(and the isData lines in the vicinity). If I understand it and the output
```
{'campaign': 'RunIISummer16MiniAODv2',
 'energy': '13',
 'extension': '',
 'format': 'MINIAOD',
 'generator': 'powheg',
 'process': 'GluGluHToTauTauM125',
 'scenario': 'PUMoriond17'}
```
correct, the generator is given as an element in the query.

**Comment by ArturAkh** [comment]
Hi Thomas,

yeah right, it searches for pattern powheg, not for the exact string. Now I understand the problem :D (sorry, a bit late right now ;))

A little bit nasty, but have you tried this regex then: "powheg$"?

http://www.regular-expressions.info/anchors.html

Cheers,

Artur

**Comment by thomas-mueller** [comment]
Yes, see above. ;-)

**Comment by thomas-mueller** [comment]
With urgent I did not mean/expect that we can solve this tonight. We might also need some input from @rfriese.

**Comment by ArturAkh** [comment]
Also in samples_run2_2016.py (in the query)? This should fix it for plotting purposes (although it would be only a hotfix...), right?

But ok, not a very proper solution.

**Comment by ArturAkh** [comment]
Another (more proper) way would be to extract this info from the Kappa files directly. As far as I know, the database entries are stored as metadata.

**Comment by rfriese** [comment]
I'm travelling until about 12:00. I'll have a Look then. CheersAm 05.07.2017 01:28 schrieb Artur Akhmetshin <notifications@github.com>:Another (more proper) way would be to extract this info from the Kappa files directly. As far as I know, the database entries are stored as metadata.

**Comment by thomas-mueller** [comment]
The plotting issue after the "change" of the queries is not this special powheg samples, but this changes the behaviour of all queries and therefore leads to problems in arbitrary samples (and we see only the first occurence before the program exists).

Taking inputs from Kappa is not really a good idea, because this would make a new skim necessary if one wants to update one of these numbers.

**Comment by rfriese** [comment]
Hi,
I propose to use "powheg-herwigpp" instead of just "powheg" for the generator entry in datasets.json and correspondingly adjust the filename. A little bashscript should be enough.

this e.g. then works:
HiggsToTauTauAnalysis.py @HiggsAnalysis/KITHiggsToTauTau/data/ArtusWrapperConfigs/Run2CPStudies_Nominal.cfg -f 1 -i root://dcache-cms-xrootd.desy.de:1094//store/user/tmuller/higgs-kit/skimming/kappa/GluGluHToTauTau_M125_13TeV_powheg/crab_GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-herwigpp/170626_204524/0000/kappa_GluGluHToTauTauM125_RunIISummer16MiniAODv2_PUMoriond17_13TeV_MINIAOD_powheg-herwigpp_6.root

@ArturAkh when adding datasets I had an automatic mechanism that checked if the identifiers are unique. Has this been removed or how else could this happen?

@thomas-mueller  "This might be related to non-optimal nicknames, but my understanding is, that manually changing nicknames is no option in our current setup (correct me if I am wrong)"

The whole point about the database is that this is possible. It's really not that hard and I've explained it several times. I get the feeling that you just do not want to understand it. There are no nicknames any more, only human-readable unique identifiers of database entries. Maybe this statement helps you to get it, if you want it.

**Comment by thomas-mueller** [comment]
Artus is completely configured via nicks. The nick we are talking about here is unique. The nick -> query -> dataset transition is due to the implementation of how the queries are done not unique. So we might have to go for this manual fix in this case and hope that the automatic mechanism works in many other cases.

**Comment by thomas-mueller** [comment]
However, I still think that it would be better to make the nick -> query -> dataset transition unique.

**Comment by thomas-mueller** [comment]
I fixed the issue partially in this commit: https://github.com/KappaAnalysis/Kappa/commit/e11112629d65f783ccb0600185e576890580f409. There are different versions of nick -> query -> dataset transitions in our code (e.g. https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/python/registerDatasetHelper.py#L281 and https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/python/datasetsHelperTwopz.py#L161) and this should maybe be followed up by the ones who duplicated these mechanisms.
