### ISSUE TITLE
muon pf Isolation 

### ISSUE THREAD

**Issue by swayand** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#6]
Hi All,

I plan to merge the embedding branch into the master. There is one larger issue I want to change.
In file: 
src/Producers/HttValidMuonsProducer.cc 
the function: 
bool HttValidMuonsProducer::AdditionalCriteria(KMuon\* muon,
                                               event_type const& event, product_type& product,
                                               setting_type const& settings) const

There i have to add some options which Benjamin has invented. But in my opinion there are some risky code behaviours. In Htt analysis most of the piplines use the "MuonIsoType" : "user", which is defined in this function. The idea behind the user iso type was to use the one implementation of the pfisolation in interface/Utility/ParticleIsolation.h. This requires four pf input collections (event.m_pfChargedHadronsNoPileUp && event.m_pfNeutralHadronsNoPileUp && event.m_pfPhotonsNoPileUp && event.m_pfChargedHadronsPileU). When this collections are not given we use the standard cmssw pf isolation as fallback, which is the default case in the Htt analysis case. First of all this is very confusing even on the config level. And second if one adds this collections (which is needed for some studies for embedding), the module uses the real user defined isolation, which is different to the default of cmssw. IMHO we should add the standard cmssw isolation we use to Artus (file: KappaAnalysis/interface/Producers/ValidMuonsProducer.h) to the "MuonIsoType" : "PF" e.g.:
else if (muonIso == MuonIso::HTTthigt)
                    validMuon = validMuon && ((((_muon)->pfIso(0.5) / (_muon)->p4.Pt()) < 0.15f) ? settings.GetDirectIso() : (!settings.GetDirectIso()));
(and of course adding the MuonIso:: HTTthigtto the interface file )
The same could be done for HTTloose. Since we are in LHC running mode the cone size and beta corr value will not change and we would simplify the configs and avoid to have strange behaviours. It is clear that you guys are very busy at the moment, therefore i can take care of if you want to have such an change. Also i will leave the src/Producers/HttValidMuonsProducer.cc such that the old configs will work. Comments are welcome ;)

Btw. can someone tell me what the config option "DirectIso" is good for?

**Comment by fcolombo** [comment]
Hi!
Was this issue solved (at least on the HTT side) in the commits 325fa7f25292cddea96a1e382e5b6ad42032b5d2 and aab6beebece22bc4abb1b2d5c3c0b64ab11d9234?

**Comment by swayand** [comment]
Hi,

in the Configs we still have the dangerous behaviour. But as you pointed out we write out the iso_value with this option. Therefore we need at least one more fix in the code.  Therefore i would like to keep this issue open. We will fix this in near future (when we have time for it).

**Comment by rfriese** [comment]
Hi Stefan, did you fix it?

**Comment by swayand** [comment]
Hi Raphael,

no i didn't fix it, and i don't plan to fix is in the near future. The reason is that we have two analysis running in this mode and I feel not involved enough to make such changes. 

I would also leave this issue open since the problems are still there, which are mostly due to the option 
MuonIsoType::USER
Because of this the the option we set in:
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/Kappa_2_1/data/ArtusConfigs/Run2Analysis/Includes/settingsMuonID.json#L10-L13
are meaningless and the only reason why we don't cut on isolation is that the default values of:
https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/Kappa_2_1/interface/HttSettings.h#L85-L88
are set such that the no isolation cut is applied. 

My suggestion would be to move all needed stuff into the ValidMuonProducer of Artus (MuonIsoType::PF), and use the MuonIsoType::USER only if we want to do something special on the isolation side. This could be us (Artur and me), when the embedding developments are finished.  

Btw. it looks like the electrons also have the same problem.

**Comment by rfriese** [comment]
still open?

**Comment by swayand** [comment]
We still have option in our configs which are not used, and leads to misunderstandings. So still open.

**Comment by rfriese** [comment]
@janekbechtel @ArturAkh  I think you inherit the responsibility for this issue. What's you statement, will there be anything to do?
